import { test, expect } from '@playwright/test';
import { pdfFixture, xmlFixture, pngFixture } from './fixtures.mjs';
test('offline local workflow: PDF, insertion, duplicate song, restore, image and MusicXML', async ({page}) => {
  const errors = []; page.on('pageerror',e => { errors.push(e.message); console.error(e.stack); });
  await page.route('**/*',route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
  await page.goto('/');
  await page.getByRole('button',{name:'첫 악보 가져오기'}).click();
  await page.locator('#files').setInputFiles([{name:'첫번째 악보.pdf',mimeType:'application/pdf',buffer:pdfFixture()},{name:'멜로디.musicxml',mimeType:'application/xml',buffer:Buffer.from(xmlFixture)},{name:'사진.png',mimeType:'image/png',buffer:pngFixture}]);
  await expect(page.locator('#library-status')).toContainText('3개 파일');
  const star=page.getByRole('button',{name:'첫번째 악보 즐겨찾기',exact:true});
  await star.click(); await expect(star).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'★ 즐겨찾기',exact:true}).click();
  await expect(page.locator('.library-row')).toHaveCount(1);
  await page.locator('#search').fill('사진'); await expect(page.locator('.library-row')).toHaveCount(0);
  await page.locator('#search').fill('');
  await page.reload(); await page.locator('#library-open').click();
  await expect(star).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'★ 즐겨찾기',exact:true}).click();
  await star.click(); await expect(page.locator('.library-row')).toHaveCount(0);
  await page.getByRole('button',{name:'전체 악보',exact:true}).click();
  await expect(page.locator('.library-row')).toHaveCount(3);
  await page.locator('.library-row').filter({hasText:'첫번째 악보'}).getByRole('button',{name:'악보 보기',exact:true}).click();
  await expect(page.locator('#stage canvas')).toBeVisible();
  await expect(page.locator('#stage')).toHaveClass(/single-page/);
  const centered = await page.locator('#stage').evaluate(el => { const outer=el.getBoundingClientRect(), inner=el.querySelector('.page-spread').getBoundingClientRect(); return Math.abs((inner.left+inner.right)/2-(outer.left+outer.right)/2)<3; });
  expect(centered).toBeTruthy();
  await expect(page.locator('#queue li')).toHaveCount(0);
  await expect(page.locator('#score-type')).toContainText('단독 보기');
  await page.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await page.reload();
  await expect(page.locator('#page-label')).toHaveText('2 / 2');
  await expect(page.locator('#queue li')).toHaveCount(0);
  await page.getByRole('button',{name:'내 악보 · 파일 추가'}).click();
  await page.locator('.library-row').filter({hasText:'첫번째 악보'}).getByRole('button',{name:'＋ 담기',exact:true}).click();
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.locator('.song-select').filter({hasText:'첫번째 악보'}).click();
  await expect(page.locator('#stage canvas')).toBeVisible();
  await expect(page.locator('#page-label')).toHaveText('1 / 2');
  expect(await page.locator('#stage').evaluate(el => el.scrollHeight <= el.clientHeight + 2)).toBeTruthy();
  await page.getByRole('button',{name:'악보 전체화면',exact:true}).click();
  await expect(page.locator('body')).toHaveClass(/performance-mode/);
  await expect(page.locator('.top')).toBeHidden();
  await page.locator('#perform-rotate').click();
  await expect(page.locator('.rotated-page')).toHaveCount(1);
  expect(await page.locator('.rotated-page').evaluate(el=>el.clientWidth>el.clientHeight)).toBeTruthy();
  await expect(page.locator('#perform-rotate')).toHaveAttribute('aria-pressed','true');
  await page.locator('#perform-rotate').click();
  await expect(page.locator('.rotated-page')).toHaveCount(0);
  await expect(page.locator('#stage canvas')).toBeVisible();
  await page.locator('#perform-exit').click();
  await expect(page.locator('.top')).toBeVisible();
  await page.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await expect(page.locator('#page-label')).toHaveText('2 / 2');
  await expect(page.getByRole('button',{name:'다음 페이지',exact:true})).toBeDisabled();
  await page.keyboard.press('ArrowLeft');
  await expect(page.locator('#page-label')).toHaveText('1 / 2');
  await page.keyboard.press('PageDown');
  await expect(page.locator('#page-label')).toHaveText('2 / 2');
  await page.getByLabel('보기 방식',{exact:true}).selectOption('vertical');
  await expect(page.locator('#stage canvas')).toHaveCount(2);
  expect(await page.locator('#stage').evaluate(el=>el.scrollHeight>el.clientHeight)).toBeTruthy();
  await page.getByLabel('보기 방식',{exact:true}).selectOption('horizontal');
  await expect(page.locator('.scroll-horizontal')).toBeVisible();
  await page.setViewportSize({width:850,height:900});
  await expect.poll(()=>page.locator('#stage').evaluate(el=>el.scrollWidth>el.clientWidth)).toBeTruthy();
  await page.locator('#stage').evaluate(el=>el.scrollLeft=el.scrollWidth);
  await expect.poll(()=>page.locator('#stage').evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
  await page.setViewportSize({width:1280,height:900});
  await page.getByLabel('보기 방식',{exact:true}).selectOption('pages');
  await page.getByRole('button',{name:'두 장 보기',exact:true}).click();
  await expect(page.locator('#stage canvas')).toHaveCount(2);
  await expect(page.locator('#page-label')).toHaveText('1–2 / 2');
  await expect(page.getByRole('button',{name:'다음 페이지',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'한 장 보기',exact:true}).click();
  await expect(page.locator('#stage canvas')).toHaveCount(1);
  await page.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await page.getByRole('button',{name:'악보 확대'}).click();
  await page.getByRole('button',{name:'＋ 곡 추가',exact:true}).click();
  await page.locator('.library-row').filter({hasText:'멜로디'}).getByRole('button',{name:'＋ 담기',exact:true}).click();
  await expect(page.locator('#queue li')).toHaveCount(2);
  await page.locator('#insert-position').selectOption('end');
  await page.locator('.library-row').filter({hasText:'첫번째 악보'}).getByRole('button',{name:'＋ 담기',exact:true}).click();
  await expect(page.locator('#queue li')).toHaveCount(3);
  await page.locator('.library-row').filter({hasText:'사진'}).getByRole('button',{name:'＋ 담기',exact:true}).click();
  await expect(page.locator('#queue li')).toHaveCount(4);
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.getByLabel('보기 방식',{exact:true}).selectOption('vertical');
  await expect(page.locator('#stage [data-item-id]')).toHaveCount(6);
  await page.locator('#stage').evaluate(el=>el.scrollTop=el.scrollHeight);
  await expect(page.locator('#score-title')).toHaveText('사진');
  await page.getByRole('button',{name:'악보 전체화면',exact:true}).click();
  await expect(page.locator('#stage img')).toHaveCount(1);
  await expect(page.locator('#stage [data-item-id]')).toHaveCount(0);
  await expect(page.locator('#stage')).toHaveCSS('overflow','clip');
  await page.locator('#stage').evaluate(el=>el.scrollTop=9999);
  expect(await page.locator('#stage').evaluate(el=>el.scrollTop)).toBe(0);
  await expect(page.locator('#score-title')).toHaveText('사진');
  await page.locator('#perform-prev-song').click();
  await expect(page.locator('#stage canvas')).toHaveCount(1);
  await page.locator('#perform-exit').click();
  await expect(page.locator('#view-mode')).toHaveValue('vertical');
  await expect(page.locator('#stage [data-item-id]')).toHaveCount(6);
  await page.getByLabel('보기 방식',{exact:true}).selectOption('horizontal');
  await expect(page.locator('.scroll-horizontal [data-item-id]')).toHaveCount(6);
  await page.locator('#stage').evaluate(el=>el.scrollLeft=0);
  await expect(page.locator('#score-title')).toHaveText('첫번째 악보');
  await page.getByLabel('보기 방식',{exact:true}).selectOption('pages');
  await expect(page.locator('#stage canvas')).toHaveCount(1);
  await page.locator('.song-select').first().click();
  await expect(page.locator('#page-label')).toHaveText('1 / 2');
  await page.getByRole('button',{name:'악보 확대'}).click();
  await page.getByRole('button',{name:'다음 페이지',exact:true}).click();
  await expect(page.locator('#page-label')).toHaveText('2 / 2');
  await expect(page.locator('#zoom-label')).toHaveText('110%');
  await page.reload();
  await expect(page.locator('#stage canvas')).toBeVisible();
  await expect(page.locator('#page-label')).toHaveText('2 / 2');
  await expect(page.locator('#zoom-label')).toHaveText('110%');
  await page.getByRole('button',{name:'악보 전체화면',exact:true}).click();
  await expect(page.locator('#perform-prev-song')).toBeDisabled();
  await page.locator('#perform-next-song').click();
  await expect(page.locator('#stage .xml-page > svg')).toBeVisible();
  await expect(page.locator('body')).toHaveClass(/performance-mode/);
  await expect(page.locator('#perform-title')).toContainText('멜로디');
  await page.locator('#perform-prev-song').click();
  await expect(page.locator('#stage canvas')).toBeVisible();
  await expect(page.locator('body')).toHaveClass(/performance-mode/);
  await page.locator('#perform-next-song').click();
  await page.locator('#perform-exit').click();
  await expect(page.locator('#stage .xml-page > svg')).toBeVisible({timeout:20000});
  await expect(page.locator('#score-title')).toHaveText('멜로디');
  await page.screenshot({path:'test-results/musicxml-desktop.png',fullPage:true});
  const handle=page.getByRole('button',{name:'2번 곡 순서 변경',exact:true});
  const from=await handle.boundingBox(),to=await page.locator('#queue li').first().boundingBox();
  await page.mouse.move(from.x+from.width/2,from.y+from.height/2);
  await page.mouse.down(); await page.mouse.move(to.x+20,to.y+5,{steps:10}); await page.mouse.up();
  await expect(page.locator('#queue .song-title').first()).toHaveText('멜로디');
  await expect(page.locator('#toast')).toContainText('곡 순서를 변경');
  await page.reload();
  await expect(page.locator('#queue .song-title').first()).toHaveText('멜로디');
  await expect(page.locator('#score-title')).toHaveText('멜로디');
  await expect(page.locator('#stage .xml-page > svg')).toBeVisible();
  await page.locator('.song-select').filter({hasText:'사진'}).click();
  await expect(page.locator('#stage img')).toBeVisible();
  await page.getByRole('button',{name:'4번 곡 콘티에서 빼기'}).click();
  await expect(page.locator('#queue li')).toHaveCount(3);
  await page.getByRole('button',{name:'새 콘티',exact:true}).click();
  await page.locator('#name-input').fill('주일 예배'); await page.getByRole('button',{name:'저장',exact:true}).click();
  await expect(page.locator('#queue li')).toHaveCount(0);
  await page.setViewportSize({width:480,height:800});
  await page.screenshot({path:'test-results/mobile-empty.png',fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});

test('settings folder path and real worship PDF', async ({page}) => {
  const folder = process.env.REAL_SCORE_FOLDER;
  test.skip(!folder, 'Optional real-file test');
  await page.goto('/');
  await page.getByRole('button',{name:'설정',exact:true}).click();
  await page.locator('#source-path').fill(folder);
  await page.getByRole('button',{name:'경로 저장',exact:true}).click();
  await expect(page.locator('#source-files')).toContainText('#001_예배합니다.pdf');
  await page.locator('.source-file').filter({hasText:'#001_예배합니다.pdf'}).locator('input').check();
  await page.getByRole('button',{name:'선택한 파일 가져오기'}).click();
  await expect(page.locator('#settings-status')).toContainText('1개 새 악보');
  await page.locator('#settings-close').click();
  await page.getByRole('button',{name:'내 악보 · 파일 추가'}).click();
  await page.locator('.library-row').filter({hasText:'#001_예배합니다'}).getByRole('button',{name:'＋ 담기',exact:true}).click();
  await page.locator('#library-close').click();
  await page.locator('.song-select').filter({hasText:'#001_예배합니다'}).click();
  await expect(page.locator('#stage canvas')).toBeVisible();
  await page.screenshot({path:'test-results/real-score-dark.png',fullPage:true});
  await page.getByRole('button',{name:'설정',exact:true}).click();
  await expect(page.locator('#source-path')).toHaveValue(folder);
});
